_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 49
            "2":
                - 1
                - 49
            "3":
                - 13
                - 15
                - 55
            "4": 3.11.11
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
